sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product dmtn-132
env:
  global:
    -
      # LTD_AWS_ID
      secure: BqNymBYHqoCvddWQjzAd3zB57EYOUKjK21NYjlnfuGSq2fuTJ7VC38uRkR5aN/xBM8tf1Lmxt3xKQCZKSPW6qJcCrtqhYZsk61et38cOq+QeiqDZnSW7dICz8+cgn5TELnUeUwI7fcTMGePvEYTAaK2wtFw3hUCPJFrdVt6VOJFsRccZgFAwQmkr4uIKArZyO0qXNTRIGixeKWKUwhhVTX4/5xPzvgxipLugrd6j2eR8ZPxEidy/TfpQB0VjdhBF/GptmX27lEwPBNYISg1WpTGYxyiMYz68mww9jFbHtL518MQUQGJfRXOBu9L5j9pcUk1mrc+5LlvgdML3RJmM0kZxl3oxw1Ykwh2hfoAJVMW77gj7eZs7jwTWOJqmkApZdMkNq2GfkYlhHffrqzCobNoYYX2V70U3pXYsF0l3zUI2RQzBL1BPNh88IIa0Q/WJ5EiFG+KSM2NlseEMi/3Yag373pfg86Ph2ewihPqb+amrhM5hWYSv++MmyDS/SCye/oae+aNTph9qadPL7dgKKCsgl/9wy2ffU9U3VaAGkDq+stKKcu40i2NXAMBxbZRjwDfFw5/p2evMjeq2QfuJZOqhjvJIRTr/heHh8usDrl/GAER5NTUAk5i+sq8peNeawvgpDPi/CRV9yFLj8ES8dz5JUptABBBnPv1yLDgA/hY=
    -
      # LTD_AWS_SECRET
      secure: SSmnetj2yk0KPia98VNqPatb3GHLhZC1mbiOE3Gs3CBD9JNfzCxBz0V1gt5JHnuaCbXDDoXMjIYYphJxdhX0o0hmPj8dusvNfld0X2ddhKWWRTGun0ymldS8FJ2vJ+yssK43vaAe6FJhbvdUeBvSkqxb3jBOUcxvlczaY+2qmCsEuhg88drmmLlJ8pI3dH25Nq7lIMpvDyDKKmesLbI7wTDTSWe2ZmcVOgk+HNdARfIjasjGCr5Upq6j+wy1P0kN8yhBeAEqzG3oHBhIxJlaDLbT32B3pKovh4cdO3cVnLRaceN1AGa2hHlIs66sSAGuAfEuVfhupIzd1/jkH4i4E5/nh0+dOWkeuoVFNe5Yw8Z6mrcy2DF+uBBiTqk2tW5++NJZjGAfCY6Mosu5LH+UlnEqhMZ7SWfMIbBbNN3RXMOzvzGK/ApZAdFEX8owOncI25XZYETajbbIfC86kCCNIhsiwZn3sOi3TGdDB5QGHCfmHT6J8GiDb5tolt/NZKI21cZcHIbynaMucL8RheUPNzKFlCa0/kRD2ZyeZfKOsfprbskQ+9oJNGJkbhDTCBzKfnxrgDlmuiAVU3aO1BGSTac3ObA7YpBwUgGLwigNS5Pm0yGYgT+bfsOPJEcnR5DJ6PueIpxw5nG2DcCH6W0hjBokOdHBa0axfAggxgdVZFM=
    -
      # LTD_USERNAME
      secure: iax0z126TXT0rt4fpiA9wdRQggdZRAz816VU5x2JRMPmrAgmOIWaXlElu5UG+7ejE17vEHfMVuXcU6gnV8riTiXrHnwmnJKPcwdbt7n/rdEeKBAiUEfU065TKHvJHAWAU9f8dzoStqcj2NWNRTU7UHyyJuVq6Gt1NySIJapdv/f5cxFdghtvW90yrWP843zZ88sWHkx9byjiQNDmfYLz8eACSRwNh8Q4f6V3hQXcFm13M4uXrjdxNdoO+5zGhJxp3QAop60oju3byUbwkjVLBFHOvkszyrlPEAUoxNEZe+1tgzPEI+lMtfk+weW7OwFVUHvPY64wcmzY5s00VaSTnXoxr+J2yts6fUl5o2qbw2Ry8EsZlaNiPLODcw3b4F650aL9Swiv/ys8BE+OvNlHogi34ZSTUfdLGE8aOU0+4mdoWP07TueuTWtlSsjV0T8xJ3SwMu37f2XFrGZP6+Z+XDn0KKo1mY1fTWww41v8DLStGrOWP9sDnoP8m7SmzEeaSPVtIW90NBBhHB1YtePwythUN+wgX+ItU2udz/55ubVcXGmDME5Vovgkv9fHpY40l+WFa3fukS/vHglfUPKvdvX2eqtdCl4L+RHD5QjEHXi35g09oHNsAYkV8l3tsCW1fjSWF1hpQT5rU7lPZl6oJZl82yYXK3MFMgu1qwk0924=
    -
      # LTD_PASSWORD
      secure: QRxc0tKdvKVXycApKQ/XWYsU3c72BsuvOtcQ0AtFbE2gzqKjrvmvDO+XyOgcO8VRmaLIHcYRTYZvp98ZZM8AHQKb/z+2Zr0JG2FTA3bgCkgLtPO11ObVJqO2a6b6RKAJeuZXBgOwRomxgemiHGI2nGEVZ6Po9hqoSGSQeQnT2qGq8cNfVQUIMW6f7np5xnst/p0VyBVRGkjq/CCqip7ZOHbjGpktA37DfLAZwXTIIxWB0X5PhxztokvxNazFsjz/dWswsHjDGIJN1lY0eVoL/zGIK/11z6fdpQT423I3Q7tR5Rv8ImXcMI4Hv+C2QIrjNppyVJaOreAVq+sJuIOOmDzkwVNZ61o+tj8bc5MMc9HaOpf/ivXguZluFGGtBM68s2siDkvtOQ+U1p8EtPyfSqPzcfSRI2zibesfFOl5dZqKQP562ksSt80B7U5sSBN/C/1qQGRiZyaOHu0SW4AehW7smPDRF9hoRfvgREszspoJKNDTB7k4Rah84WV7vLX5I5Cbh1HNaKTlXCc93WeMEQrpQW+gyf1ctHD+nYEf5J1faaypAGLAecdkszOSlT6LveDZLrSkVtNfbYip1Lz4XUitukUGtUYNut3I6SGmwhPjvq40PEybQMKAp35NdFjKrMbvq3mR8S97iti/Sy5jsnBgNm4CMtDgqFXXu90fYkY=
